setwd("/Users/veronicapagowski/Desktop/MOLECOL/F6_PSMC/PSMC")
library(ggplot2)
library(scales)

# Load in different population datasets #

### First, a few notes on the chosen parameters ###

# These were generated by using psmc_plot.pl, with an initial generation time of 5 years (anecdotal time to reach sexual maturity when you're not trying too hard to keep them happy...). 
# Since we are going to plot generations ago (generation time in the wild sort of unclear for Patiria), we're going to scale down again. 

# generation time = 5 years and mutation rate of 3.8e-9 (same as Hart paper, but these were non-COI mitochondrial rates), we get a split at 100 kya. 
# Germ-line mutation rates for Patiria are unclear and we might expect them to be lower than mitochondrial rates...
# but we are going to use the higher Acanthaster germ line rate of 9.13e-9, since it's the only species for which there is a recent precise estimate for this number, to my knowledge. 

# Given we are not certain about wild generation time (lab studies suggest 2 years under optimal conditions, but for Pycnopodia modelling suggests generation times of 20+ years with sexual maturity at 3yrs)...
# All to say that estimates for these values are truly all over the place. We show here that that population across Queen Charlotte Sound (and later those in Central BC, see supplement) diverge from other populations and experience a bottleneck
# The timeline of this event is really not clear without good approximations for these values, but supports the hypotheses raised by past work that these populations don't mix much.  

# Now load in different population datasets from psmc_plot with -R parameter to save intermediate files (the ones used here, so we can use pretty colors and plot everything together) #

HG4 <- read.table("23442Pal_G4_S191_fround_9.13e-9.0.txt") #Haida Gwaii (Hi)
HG4_df <- data.frame(ya = HG4[-1, 1] , ne = HG4[-1, 2])
Bam <- read.table("23442Pal_B4_S190_fround_9.13e-9.0.txt") #Bamfield 
Bam_df <- data.frame(ya = Bam[-1, 1] , ne = Bam[-1, 2])
HG6 <- read.table("23442Pal_G6_S192_35X_fround_9.13e-9.0.txt") #Haida Gwaii (Hi), sample 2, downsampled to 35x since it sequenced at slightly higher coverage
HG6_df <- data.frame(ya = HG6[-1, 1] , ne = HG6[-1, 2])
FB <- read.table("23442Pal_F3_S189_fround_9.13e-9.0.txt") #Fort Bragg
FB_df <- data.frame(ya = FB[-1, 1] , ne = FB[-1, 2])
H <- read.table("23442Pal_H9_S186_fround_9.13e-9.0.txt") #Hazard Canyon
H_df <- data.frame(ya = H[-1, 1] , ne = H[-1, 2])
Mon <- read.table("23442Pal_M1_S188_fround_9.13e-9.0.txt") #Monterey
Mon_df <- data.frame(ya = Mon[-1, 1] , ne = Mon[-1, 2])
SB <- read.table("23442Pal_SB-4_S187_fround_9.13e-9.0.txt") #Santa Barbara
SB_df <- data.frame(ya = SB[-1, 1] , ne = SB[-1, 2])

# Create a list to store data frames for bootstrap iterations
boot_list_HG6 <- list()
boot_list_HG4 <- list()
boot_list_FB <- list()
boot_list_H <- list()
boot_list_Mon <- list()
boot_list_SB <- list()
boot_list_Bam <- list()

#Next, make loops to load in all these files (bootraps from sub-sampling the fasta file used for PSMC)
#HG6
for (i in 0:99) {
  path <- paste0("23442Pal_G6_S192_35X_fround_9.13e-9.", i, ".txt")
  boot.iter <- read.table(path)
  ya <- boot.iter[-1, 1]
  ne <- boot.iter[-1, 2]
  boot_list_HG6[[i+1]] <- data.frame(ya = ya[ya > 1000], ne = ne[ya > 1000], iter = i)
}
#HG4
for (i in 0:99) {
  path <- paste0("23442Pal_G4_S191_fround_9.13e-9.", i, ".txt")
  boot.iter <- read.table(path)
  ya <- boot.iter[-1, 1]
  ne <- boot.iter[-1, 2]
  boot_list_HG4[[i+1]] <- data.frame(ya = ya[ya > 1000], ne = ne[ya > 1000], iter = i)
}
#FB
for (i in 0:99) {
  path <- paste0("23442Pal_F3_S189_fround_9.13e-9.", i, ".txt")
  boot.iter <- read.table(path)
  ya <- boot.iter[-1, 1]
  ne <- boot.iter[-1, 2]
  boot_list_FB[[i+1]] <- data.frame(ya = ya[ya > 1000], ne = ne[ya > 1000], iter = i)
}
#H
for (i in 0:99) {
  path <- paste0("23442Pal_H9_S186_fround_9.13e-9.", i, ".txt")
  boot.iter <- read.table(path)
  ya <- boot.iter[-1, 1]
  ne <- boot.iter[-1, 2]
  boot_list_H[[i+1]] <- data.frame(ya = ya[ya > 1000], ne = ne[ya > 1000], iter = i)
}

#Mon
for (i in 0:99) {
  path <- paste0("23442Pal_M1_S188_fround_9.13e-9.", i, ".txt")
  boot.iter <- read.table(path)
  ya <- boot.iter[-1, 1]
  ne <- boot.iter[-1, 2]
  boot_list_Mon[[i+1]] <- data.frame(ya = ya[ya > 1000], ne = ne[ya > 1000], iter = i)
}

#SB
for (i in 0:99) {
  path <- paste0("23442Pal_SB-4_S187_fround_9.13e-9.", i, ".txt")
  boot.iter <- read.table(path)
  ya <- boot.iter[-1, 1]
  ne <- boot.iter[-1, 2]
  boot_list_SB[[i+1]] <- data.frame(ya = ya[ya > 1000], ne = ne[ya > 1000], iter = i)
}
#Bam
for (i in 0:99) {
  path <- paste0("23442Pal_B4_S190_fround_9.13e-9.", i, ".txt")
  boot.iter <- read.table(path)
  ya <- boot.iter[-1, 1]
  ne <- boot.iter[-1, 2]
  boot_list_Bam[[i+1]] <- data.frame(ya = ya[ya > 1000], ne = ne[ya > 1000], iter = i)
}

# Combine all bootstrap data frames
boot_df_HG6 <- do.call(rbind, boot_list_HG6)
boot_df_HG4 <- do.call(rbind, boot_list_HG4)
boot_df_FB <- do.call(rbind, boot_list_FB)
boot_df_H <- do.call(rbind, boot_list_H)
boot_df_Mon <- do.call(rbind, boot_list_Mon)
boot_df_SB <- do.call(rbind, boot_list_SB)
boot_df_Bam <- do.call(rbind, boot_list_Bam)

combined_boot_df <- rbind(
  cbind(do.call(rbind, boot_list_HG6), Population = "Haida Gwaii 2"),
  cbind(do.call(rbind, boot_list_HG4), Population = "Haida Gwaii 1"),
  cbind(do.call(rbind, boot_list_FB), Population = "Fort Bragg"),
  cbind(do.call(rbind, boot_list_H), Population = "Hazard Canyon"),
  cbind(do.call(rbind, boot_list_Mon), Population = "Monterey"),
  cbind(do.call(rbind, boot_list_SB), Population = "Santa Barbara"),
  cbind(do.call(rbind, boot_list_Bam), Population = "Bamfield")
)
# Create the plot
custom_order<-c("Haida Gwaii 1","Haida Gwaii 2","Bamfield","Fort Bragg","Monterey","Hazard Canyon", "Santa Barbara")          
combined_boot_df$Population <- factor(combined_boot_df$Population, levels = custom_order)
cols2 <- c("deeppink4","deeppink3","darkorange","lightgoldenrod3","olivedrab3","mediumseagreen","dodgerblue")


plt_fig6a<-ggplot() +
  geom_step(data = combined_boot_df, 
            aes(x = 0.2*ya, y = ne*10000, group = interaction(Population, iter), color = Population), #output scaled by default to 10^4, multiplied by 0.2 to scale back down to generations not years
            alpha = 0.1, size = 0.2) +
  geom_step(data = subset(combined_boot_df, iter == 0), 
            aes(x = 0.2*ya, y = ne*10000, group = Population, color=Population),
            size = 0.8,alpha = 0.7) +
  scale_color_manual(values = cols2) +
  scale_x_log10(limits = c(1500, 1000000),expand = c(0, 0), #og scales to 10000 to 10000000 gen=5
                breaks = c(1e4, 1e5, 1e6, 1e7),
                labels = trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(limits = c(0, 2e5),expand = c(0, 0), # Linear scale starting from 0
                     breaks = seq(0, 3e5, by = 0.5e5),
                     labels = label_number(scale = 1e-5)) + #also scale by 10^3 because easier for me
  labs(x = "Generations ago",  y = expression(N[e]~"x"~10^5), title = "") +
  theme_minimal() +
  theme_bw()

#annotate
plt_fig6a <- plt_fig6a  +
  annotate(
    "rect",
    xmin = 1800, xmax = 31623, ymin = 5000, ymax = 190000, 
    fill = NA, color = "black", linetype = "dashed", linewidth = 0.5) #+
  #annotate(
  #  "text",
  #  x = 180000,  # X-coordinate near line
  #  y = 180000,  # Y-coordinate near line
  #  label = expression(mu == 9.13e-9),
  #  color = "black", size = 4)


ggsave(filename = "Figure6a_PSMC_final.png", 
       plot = plt_fig6a, 
       width = 6, 
       height =5, 
       units = "in",
       dpi = 300)

#Save as an r object to plot later
saveRDS(plt_fig6a+ theme(legend.position = "none"), file = "/Users/veronicapagowski/Desktop/MOLECOL/F6_PSMC/plt_fig6a.rds")

