setwd("/Users/veronicapagowski/Desktop/MOLECOL/F7_Admix")
library(tidyverse) 
library(RColorBrewer)
minK=2
maxK=4 #up to 4, but 4 plotted since we are really mostly interested in seeing the range gap and genetic split

#Load in files generated by ngsADMIX
prefix="Pmin_lc_geno_e6_maf0.05_OGsiteprune_R1+R2_minind117_K"
suffix=".qopt"
tbl<-lapply(minK:maxK, function(x) read.table(paste0(prefix,x,suffix)))
tbl2 <-list()

#set labels
sample_id<-read.csv("old_new_bams_rmreseq_bam.csv")
pop<-sample_id$group

#Loop through Ks and match up labels
for(i in c(1:3)){
  admix.id<-tbl[[i]]
  admix.id = as.data.frame(cbind(pop, admix.id))
  admix.id<-subset(admix.id,admix.id$pop!="Fort Bragg (Hi)") #only a few samples here, so we'll ommit
  admix.id<-subset(admix.id,admix.id$pop!="San Diego (Hi)") #only a few samples here, so we'll ommit
  custom_order2<-c("Haida Gwaii (Hi)","Central BC (Hi)","Winter Harbor (Hi)","Ucluelet","Bamfield","Bamfield (Hi)","Fort Bragg","Fort Bragg (AQ)","Monterey","Hazard Canyon","Santa Barbara","Santa Barbara (AQ)","LA (AQ)","San Diego (AQ)","Ensenada")  
  #custom_order2<-c("Haida Gwaii (Hi)","Central BC (Hi)","Winter Harbor (Hi)","Ucluelet","Bamfield","Bamfield (Hi)","Fort Bragg","Fort Bragg (Hi)","Fort Bragg (AQ)","Monterey","Hazard Canyon","Santa Barbara","Santa Barbara (AQ)","LA (AQ)","San Diego (AQ)","San Diego (Hi)","Ensenada") 
  #use above to see all
  admix.id$pop <- factor(admix.id$pop, levels = custom_order2)
  admix.id$pop_n<-admix.id$pop
  levels(admix.id$pop_n)<-c(1:length(levels(admix.id$pop)))
  admix.id$pop_n<-as.integer(as.character(admix.id$pop_n))
  admix.id<-admix.id %>%
    arrange(pop_n)
  tbl2[[i]]<-admix.id
}

#Generate spaces between samples in the plot
rep <- as.vector(table(admix.id$pop_n))
spaces <- 0
for(i in 1:length(rep)){
  spaces <- c(spaces, rep(0, rep[i]-1), 0.5)
}
spaces <- spaces[-length(spaces)]

get_colors <- function(n) {
  custom_colors <- c("#EEB4B4","#6892CD","plum4","cadetblue","darkseagreen3")
  if (n <= 5) {
    return(custom_colors[1:n])
  } else {
    return(colorRampPalette(custom_colors)(n))
  }
}

# First plot
get_colors <- get_colors(maxK)

pop_counts <- table(admix.id$pop)
pop_centers <- cumsum(pop_counts) - (pop_counts / 2)


pdf(file = "Figure7_final.pdf", width = 7, height = 4.2)
##### Plot all plots #####
par(mfrow=c(maxK-1,1), 
    mar=c(1,1,0,0), 
    oma=c(8,1,9,1),  # Increased bottom margin from 2 to 4
    mgp=c(0,0.8,0), 
    xaxs="i", 
    cex.lab=1.1, 
    cex.axis=1.5)

bp <- barplot(t(as.matrix(subset(tbl2[[1]], select=V1:V2))), col=get_colors, xaxt="n", border=NA, ylab=paste0("K=",minK), yaxt="n", space=spaces)
barplot(t(as.matrix(subset(tbl2[[2]], select=V1:V3))), col=get_colors, xaxt="n", border=NA, ylab=paste0("K=",minK+1), yaxt="n", space=spaces)
barplot(t(as.matrix(subset(tbl2[[3]], select=V1:V4))), col=get_colors, xaxt="n", border=NA, ylab=paste0("K=",minK+2), yaxt="n", space=spaces)
#barplot(t(as.matrix(subset(tbl2[[4]], select=V1:V5))), col=get_colors, xaxt="n", border=NA, ylab=paste0("K=",minK+3), yaxt="n", space=spaces)

#Draw the extended x-axis line
abline(h = 0, col = "black", lwd = 1)
axis(1, at=bp[pop_centers], labels=levels(admix.id$pop), las=2, cex.axis=1, lwd.ticks=1,lwd = 0)

dev.off() 
